- name: Testing Ansible Localhost
  hosts: localhost
  tasks:
    - name: execute command 'ls'
      changed_when: false
      command: ls

    - name: check if file exist
      stat:
        path: "{{ directory_file }}/test.txt"
      register: stat_file

    - name: Creates directory
      ansible.builtin.file:
        path: "{{ directory_file }}"
        state: directory

    - name: create file on home dir
      command: touch "{{ directory_file }}/test.txt"
      changed_when: not stat_file.stat.exists

    - name: insert text line
      lineinfile:
        path:  "{{ directory_file }}/test.txt"
        line: Hello World
        state: present

    - name: insert after text line
      lineinfile:
        path:  "{{ directory_file }}/test.txt"
        line: Hello World 2
        insertafter: 2
        state: present
    
    - name: Insert a line after a specific pattern
      lineinfile:
        path:  "{{ directory_file }}/test.txt"
        line: "This is the new line"
        insertafter: "^Pattern to match"
    
 